### ISSUE TITLE
Get the intensity result of the model from `ampform` and put it in weights of Dalitz Plot

### ISSUE THREAD

**Issue by shenvitor** [ComPWA/gluex-nstar#32]
### Problem description

Find a way to get the model.intensity to be used in weighted of hist2d in https://github.com/ComPWA/gluex-nstar/pull/28 after phase space and data sample Dalitz plots

### Proposed solution

maybe something more than `model.intensity`

**Comment by redeboer** [comment]
You mean you should only plot the model by histogramming over phase space with the model (intensity function) as phase space, right? Data generation is not needed for now, as we only want to investigate model behavior (see also #31).

**Comment by shenvitor** [comment]
The data sample is extra I know.
Just thinking about how to make the model use the phase space sample the output the intensity then I feed it to the weights in hist2d

**Comment by redeboer** [comment]
Essentially just e.g.

```python
plt.hist2d(
    phsp["m12"],
    phsp["m23"],
    weights=intensity_func(phsp)
)
```

with `phsp` a [`DataSample`](https://tensorwaves.readthedocs.io/0.4.x/api/tensorwaves.interface/#tensorwaves.interface.DataSample).

**Comment by shenvitor** [comment]
Closes by https://github.com/ComPWA/gluex-nstar/pull/28/commits/7585cc5d3c5a1be4b5f427c0f934029bfb8cc356
