### ISSUE TITLE
Mass for Initial state pgamma would be different for decay to K⁺π⁰Λ

### ISSUE THREAD

**Issue by shenvitor** [ComPWA/gluex-nstar#35]
Compared to ηπ⁰p decays the values of $m_0$ should be different...
So maybe I need to recompute the values and then redo the add custom particle
issue to be addressed in #29 soon

**Comment by redeboer** [comment]
Probably best to create a center-of-mass energy variable and set the mass of the virtual pgamma state to that variable. Then you can just update that value depending on the data you need.

Incidentally, if you set the construct phase space generator from the initial and final state particles, the generated phase space is automatically updated accordingly.

**Comment by shenvitor** [comment]
Anyway, I overthought. The value is still the same if the beam energy in the lab frame for p$\gamma$ is the same.
