### ISSUE TITLE
Formulate kinematics variables symbolically with SymPy and AmpForm

### ISSUE THREAD

**Issue by shenvitor** [ComPWA/gluex-nstar#36]
Formulate the conversion from four-momenta to Mandelstam variables and helicity angles symbolically. This is required to visualize the model over a phase space sample.

**Comment by redeboer** [comment]
> issue to be solved in [DOC: form amplitude models in symbolic expression for PWA101 channel #13](https://github.com/ComPWA/gluex-nstar/pull/13)

Probably better to only formulate the amplitude model in that PR for now. You can then address this issue through a separate PR where you visualize the model (for which you need a momentum-to-angle `DataTransformer`).

**Comment by redeboer** [comment]
For the implementation, have a look at this:
https://ampform.readthedocs.io/0.15.x/usage/kinematics.html#lorentz-vectors
