### ISSUE TITLE
Add Ruff configuration

### ISSUE THREAD

**Issue by redeboer** [ComPWA/gluex-nstar#40]
Ruff is currently using the default configuration, but there are many [additional rules](https://docs.astral.sh/ruff/rules/) that can are quite useful. (For the open PRs, we need [`ERA001`](https://docs.astral.sh/ruff/rules/commented-out-code/) 😁 ).

See for example [which rules AmpForm selects](https://github.com/ComPWA/ampform/blob/7d5e50244715fc0976e9658446669defdda10904/pyproject.toml#L286-L318). But that's a bit too much, for now just activate ERA001

**Comment by shenvitor** [comment]
[UP034](https://docs.astral.sh/ruff/rules/extraneous-parentheses/) To be added too

**Comment by redeboer** [comment]
I would even select `ALL`. [Since Ruff v0.5.0](https://astral.sh/blog/ruff-v0.5.0#selecting-all-now-excludes-deprecated-rules), it's quite stable to use that. Any rules we do not like can then be deactivated.
